version: '3.5'

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=192.168.171.150
      - DB_SERVER_PORT=31432
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=datalake
      - POSTGRES_PASSWORD=e9sAtZ4aBO
    ports:
      - "10051:10051"

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
    container_name: zabbix-web
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=192.168.171.150
      - DB_SERVER_PORT=31432
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=datalake
      - POSTGRES_PASSWORD=e9sAtZ4aBO
      - PHP_TZ=Asia/Dubai
    ports:
      - "8080:8080"
      # - "8443:8443"
    depends_on:
      - zabbix-server
    volumes:
      - /etc/ssl/nginx:/etc/ssl/nginx:ro
###